site_name: Hemant Sharma
theme:
  name: material
  palette:
    primary: black
    accent: red
  icon:
    logo: material/router
    repo: fontawesome/brands/git-alt
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.top
    - toc.integrate
repo_url: https://github.com/hmntsharma/openbmp-crpd
repo_name: hmntsharma/openbmp-crpd
edit_uri: ""
